Movie Front/MovieManagement/MovieManagement/Controllers/LandingPageController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieManagement.ViewModels;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MovieManagement.Controllers
{
    public class LandingPageController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        public LandingPageController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> LandingPage(int limit, int offset, string searchName)
        {
            if (limit <= 0)
            {
                limit = 6;
            }
            if (offset <= 0)
            {
                offset = 0;
            }
            if (searchName == null)
            {
                searchName = "";
            }
            MovieRequestViewModels movieRequestViewModels = new MovieRequestViewModels();
            movieRequestViewModels.Limit = limit;
            movieRequestViewModels.Offset = offset;
            movieRequestViewModels.SearchName = searchName;

            string apiUrl = "https://localhost:7063/api/Movie/allMovie";
            string queryString = $"?limit={movieRequestViewModels.Limit}&offset={movieRequestViewModels.Offset}" +
                $"&searchName={Uri.EscapeDataString(movieRequestViewModels.SearchName)}";

            HttpClient httpClient = new HttpClient();
            var response = await httpClient.GetAsync(apiUrl + queryString);
            var responseString = response.Content.ReadAsStringAsync();
            List<MovieViewModels>? movies = new List<MovieViewModels>();
            if (response.IsSuccessStatusCode)
            {
                movies = JsonConvert.DeserializeObject<List<MovieViewModels>>(responseString.Result);
            }
            return View(movies);
        }

        public async Task<IActionResult> Favourite(int limit, int offset, string searchName)
        {
            if (limit <= 0)
            {
                limit = 9;
            }
            if (offset <= 0)
            {
                offset = 0;
            }
            if (searchName == null)
            {
                searchName = "";
            }
            MovieRequestViewModels movieRequestViewModel = new MovieRequestViewModels();
            movieRequestViewModel.Limit = limit;
            movieRequestViewModel.Offset = offset;
            movieRequestViewModel.SearchName = searchName;
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                movieRequestViewModel.UserId = user?.Id;
            }
            string apiUrl = "https://localhost:7063/api/movie/getuserfavourite";
            string queryString = $"?limit={movieRequestViewModel.Limit}&offset={movieRequestViewModel.Offset}" +
                $"&searchName={Uri.EscapeDataString(movieRequestViewModel.SearchName)}&UserId={movieRequestViewModel.UserId}";

            HttpClient httpClient = new HttpClient();
            var response = await httpClient.GetAsync(apiUrl + queryString);
            var responseString = response.Content.ReadAsStringAsync();
            List<MovieViewModels>? movies = new List<MovieViewModels>();
            if (response.IsSuccessStatusCode)
            {
                movies = JsonConvert.DeserializeObject<List<MovieViewModels>>(responseString.Result);
            }
            ViewBag.Search = movieRequestViewModel.SearchName;
            return View(movies);
        }

        
    }
}

Movie Front/MovieManagement/MovieManagement/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Video Stream</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="LandingPage" asp-action="LandingPage">Video Streamt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @if(SignInManager.IsSignedIn(User))
                       {
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="AddMovie">Add Movie</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="LandingPage" asp-action="Favourite">Favourite List</a>
                            </li>
                       }

                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>